/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thayTai;

import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nhipham
 */
public class Cau9 extends javax.swing.JFrame {
    private Vector <String> items = new Vector();
    /**
     * Creates new form Cau9
     */
    public Cau9() {
        initComponents();
        
    }
    private boolean isPrime(int num) {
        if (num <= 1) {
            return false;
        }
        for (int i = 2; i <= Math.sqrt(num); i++) {
            if (num % i == 0) {
                return false;
            }
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        todenchanBtn = new javax.swing.JButton();
        todenleBtn = new javax.swing.JButton();
        todenngtoBtn = new javax.swing.JButton();
        botodenBtn = new javax.swing.JButton();
        xoaBtn = new javax.swing.JButton();
        tongBtn = new javax.swing.JButton();
        nhapBtn = new javax.swing.JButton();
        nhapText = new javax.swing.JTextField();
        soamCheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        todenchanBtn.setText("Tô Đen Số Chẵn");
        todenchanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todenchanBtnActionPerformed(evt);
            }
        });

        todenleBtn.setText("Tô Đen Số Lẻ");
        todenleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todenleBtnActionPerformed(evt);
            }
        });

        todenngtoBtn.setText("Tô Đen Số Nguyên Tố");
        todenngtoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todenngtoBtnActionPerformed(evt);
            }
        });

        botodenBtn.setText("Bỏ Tô Đen");
        botodenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botodenBtnActionPerformed(evt);
            }
        });

        xoaBtn.setText("Xoá Các Giá Trị Đang Tô Đen");
        xoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaBtnActionPerformed(evt);
            }
        });

        tongBtn.setText("Tổng giá trị trong jList");
        tongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tongBtnActionPerformed(evt);
            }
        });

        nhapBtn.setText("Nhập");
        nhapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapBtnActionPerformed(evt);
            }
        });

        soamCheck.setText("Cho nhập số âm");
        soamCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soamCheckActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list);

        exit.setText("Đóng Chương Trình");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(todenchanBtn)
                            .addComponent(todenngtoBtn)
                            .addComponent(botodenBtn)
                            .addComponent(xoaBtn)
                            .addComponent(tongBtn)
                            .addComponent(todenleBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nhapBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nhapText, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(soamCheck))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhapBtn)
                    .addComponent(nhapText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soamCheck))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(todenchanBtn)
                        .addGap(18, 18, 18)
                        .addComponent(todenleBtn)
                        .addGap(18, 18, 18)
                        .addComponent(todenngtoBtn)
                        .addGap(18, 18, 18)
                        .addComponent(botodenBtn)
                        .addGap(18, 18, 18)
                        .addComponent(xoaBtn)
                        .addGap(18, 18, 18)
                        .addComponent(tongBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void todenleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todenleBtnActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < items.size(); i++) {
            int num = Integer.parseInt(items.get(i));
            if (num % 2 == 1 || num % -2 == 1) {
                list.addSelectionInterval(i, i);
            }
        }
    }//GEN-LAST:event_todenleBtnActionPerformed

    private void todenngtoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todenngtoBtnActionPerformed
        // TODO add your handling code here:
         for (int i = 0; i < items.size(); i++) {
            int num = Integer.parseInt(items.get(i));
            if (isPrime(num)) {
                list.addSelectionInterval(i, i);
            }
        }
    }//GEN-LAST:event_todenngtoBtnActionPerformed

    private void nhapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapBtnActionPerformed
        // TODO add your handling code here
       String text = nhapText.getText();
    try {
        int num = Integer.parseInt(text);
        if (soamCheck.isSelected() || num >= 0) {
            items.add(text);
            list.setListData(items);
            nhapText.setText("");
        } else {
            JOptionPane.showMessageDialog(this,
                "Please check to allow negative numbers or enter a non-negative number.",
                "Message",
                JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Please enter a valid integer.",
            "Message",
            JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_nhapBtnActionPerformed

    private void soamCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soamCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soamCheckActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
       int confirmation = JOptionPane.showConfirmDialog(this,
        "Are you sure to close the programm>?",
        "Confirm closing programm",
        JOptionPane.YES_NO_OPTION);

    if (confirmation == JOptionPane.YES_OPTION) {
        System.exit(0); 
    }
    }//GEN-LAST:event_exitActionPerformed

    private void todenchanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todenchanBtnActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < items.size(); i++) {
            int num = Integer.parseInt(items.get(i));
            if (num % 2 == 0 || num % -2 == 0) {
                list.addSelectionInterval(i, i);
            }
        }
    }//GEN-LAST:event_todenchanBtnActionPerformed

    private void tongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tongBtnActionPerformed
        // TODO add your handling code here:
        int sum = 0;
        for (String item : items) {
            int num = Integer.parseInt(item);
            sum += num;
        }
        JOptionPane.showMessageDialog(this, "Tổng giá trị trong jList: " + sum, "Tính Tổng", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_tongBtnActionPerformed

    private void botodenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botodenBtnActionPerformed
        // TODO add your handling code here:
        list.clearSelection();
    }//GEN-LAST:event_botodenBtnActionPerformed

    private void xoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaBtnActionPerformed
        // TODO add your handling code here:
        int[] selectedIndices = list.getSelectedIndices();
        for (int i = selectedIndices.length - 1; i >= 0; i--) {
            int selectedIndex = selectedIndices[i];
            items.remove(selectedIndex);
        }
        list.setListData(items);
    }//GEN-LAST:event_xoaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cau9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cau9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cau9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cau9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cau9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botodenBtn;
    private javax.swing.JButton exit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JButton nhapBtn;
    private javax.swing.JTextField nhapText;
    private javax.swing.JCheckBox soamCheck;
    private javax.swing.JButton todenchanBtn;
    private javax.swing.JButton todenleBtn;
    private javax.swing.JButton todenngtoBtn;
    private javax.swing.JButton tongBtn;
    private javax.swing.JButton xoaBtn;
    // End of variables declaration//GEN-END:variables
}
